name: Build and deploy JAR app to Azure Web App - concentrate

on:
  push:
    branches:
      - KotlinConcentrate_feature/ProfileManagement-ThuongNV
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin' 
          java-package: jdk
          cache: gradle    

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-app
          path: build/libs/concentrate-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: kotlin-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5A39758688049B9A566B0F99CB746A3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA8450AB97B34EEE8B65EF63A9D57CB7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ED285243FDD3496FB4CB2C300B8E275A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'concentrate'
          slot-name: 'Production'
          package: '*.jar'
